my_blog_home:
    pattern:  /
    defaults  { _controller: ExblogBundle:Article:affhome }

my_blog_add_category:
    pattern:  add/category/
    defaults: { _controller: ExblogBundle:Category:edit }

my_blog_edit_category:
    pattern:  /edit/category/{id}
    defaults: { _controller: ExblogBundle:Category:edit }
    requirements:
        id:  \d+

my_blog_delete_category:
    pattern:  /delete/category/{id}
    defaults: { _controller: ExblogBundle:Category:delete }
    requirements:
        id:  \d+

my_blog_affall_article:
    pattern:  /{category}
    defaults: { _controller: ExblogBundle:Article:affall }

my_blog_affone_article:
    pattern:  /article/{id}
    defaults: { _controller: ExblogBundle:Article:aff }
    requirements:
        id:  \d+

my_blog_add_article:
    pattern:  add/article/
    defaults: { _controller: ExblogBundle:Article:edit }

my_blog_edit_article:
    pattern:  /edit/article/{id}
    defaults: { _controller: ExblogBundle:Article:edit }
    requirements:
        id:  \d+

my_blog_delete_article:
    pattern:  /delete/article/{id}
    defaults: { _controller: ExblogBundle:Article:delete }
    requirements:
        id:  \d+

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password  